In [3]:
!pip3 install numpy

Defaulting to user installation because normal site-packages is not writeable
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.2/21.2 MB 41.0 MB/s eta 0:00:0000:0100:01


In [16]:
import numpy as np
x = np.arange(10)
print(f"x = {x}")
y = x[1:3]  # creates a view
print(f"y = {y}")
x[1:3] = [10, 11]
print(f"x = {x}")
print(f"y = {y}")


x = [0 1 2 3 4 5 6 7 8 9]
y = [1 2]
x = [ 0 10 11  3  4  5  6  7  8  9]
y = [10 11]


4870780272

In [17]:
id(x)
# id(y)

4836584752

In [18]:
# id(x)
id(y)

4870780272

In [8]:
import numpy as np
x = np.arange(9).reshape(3, 3)
print(f"x = {x}")
y = x[[1, 2]]
print(f"y = {y}")
y.base is None


x[[1, 2]] = [[10, 11, 12], [13, 14, 15]]
print(f"x = {x}")
print(f"y = {y}")

x = [[0 1 2]
 [3 4 5]
 [6 7 8]]
y = [[3 4 5]
 [6 7 8]]
x = [[ 0  1  2]
 [10 11 12]
 [13 14 15]]
y = [[3 4 5]
 [6 7 8]]
